version: 2
jobs:
  build-go:
    docker:
      - image: circleci/golang:1.9
        environment:
            GOFLAGS: "-mod=vendor"
    working_directory: /go/src/github.com/rikisan1993/coverall-learning
    steps:
      - checkout
      - run:
          name: run go tests
          command: |
            go fmt ./...
            go vet ./...
            GOFLAGS=-mod= go get github.com/mattn/goveralls
            go test -v -cover -race -timeout=60s -coverprofile=./coverage.out $(go list ./...)
            GOFLAGS=-mod= goveralls -coverprofile=./coverage.out -service=circle-ci -repotoken=iZEBTcZGlOTz6r2o2sk64OEkYEbLrlVTZ
    
  build-ng:
    docker:
      - image: circleci/node:8.12-browsers
    steps:
      - checkout
      - run:
          name: run ng test
          command: |
            cd web/ui
            npm i
            npm run test

workflows:
  version: 2
  build-test-release:
    jobs:
      - build-go:
          filters:
            branches:
              only: master
      - build-ng:
          filters:
            branches:
              only: master